language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t karnaugh101/docker-react Dockerfile.dev .
script:
    - docker run -e CI=true karnaugh101/docker-react npm run test